repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.6
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        exclude: ^tests/(playwright|integration|e2e)/
        additional_dependencies:
          - click>=8.1
          - jinja2>=3.1
          - platformdirs>=3.0
          - pyyaml>=6.0
          - requests>=2.28
          - types-PyYAML>=6.0.12.20240917
          - types-requests>=2.31.0.10
  - repo: local
    hooks:
      - id: pytest-unit-coverage
        name: pytest-unit-coverage
        entry: python3
        language: python
        pass_filenames: false
        args:
          - -c
          - "import os; os.environ['PYTHONPATH'] = 'src'; import subprocess; subprocess.run(['python3', '-m', 'pytest', 'tests/unit', 'tests/integration', 'tests/e2e', '--cov=pwa_forge', '--cov-fail-under=60', '--cov-report=term-missing', '-q'], check=True)"
        additional_dependencies:
          - pytest>=7.0
          - pytest-cov>=4.0
          - click>=8.1
          - jinja2>=3.1
          - platformdirs>=3.0
          - pyyaml>=6.0
          - requests>=2.28
